### ISSUE TITLE
CREDIT taxonomy issue

### ISSUE THREAD

**Issue by estedeahora** [JATS4R/jats-schematrons#25]
Hello.

I am using the XML Validator, but I have encountered a problem in the CREDIT taxonomy. Following the recommendations on the Jats4R page it is stated in the table and in the example that URLs starting with "https" should be used, however the validator only recognises addresses starting with "http". I think it is a bug and that it should be possible to use both options.

I think this would be solved by adding to [this file](https://github.com/JATS4R/jats-schematrons/blob/master/schematrons/1.0/credit-roles.xml) the "https versions" of the URLs(along with the http ones so that they still work). However I don't know Schematron and I'm not sure this is the right solution.

Pablo

**Comment by fred-atherden** [comment]
Hi Pablo,

Thanks for the bug report. You're right, these checks should be asserting the presence of `https` in the URLs instead of `http`. 

I've opened a PR to fix the issue - https://github.com/JATS4R/jats-schematrons/pull/26.
