### ISSUE TITLE
Issue with the <break> element.

### ISSUE THREAD

**Issue by estedeahora** [JATS4R/jats-schematrons#27]
Hi!

I found a small problem in the JATS4r validator. The problem is that when I use the `<break>` element, the validator generates an error and does not run the validator. 

![image](https://github.com/JATS4R/jats-schematrons/assets/56130517/29a3bb3b-2327-4275-a632-a07014102b6f)

This element is allowed by [DTD 1.3](https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/break.html). I understand that it is unusual to use it in a body text, as the purpose of jats-xml is not to reproduce the display. However, in a table it can be an important element.

I send you a minimal example

Thanks again for your work!

```
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE article PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.3 20210610//EN" "https://jats.nlm.nih.gov/publishing/1.3/JATS-journalpublishing1-3.dtd">

<article xmlns:ali="http://www.niso.org/schemas/ali/1.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:mml="http://www.w3.org/1998/Math/MathML" dtd-version="1.3" specific-use="~!gurí_(+Pandoc)" article-type="introduction" xml:lang="es">
<front>
<journal-meta>
<journal-id></journal-id>
<journal-title-group>
<journal-title specific-use="original" xml:lang="es">My journal</journal-title>
</journal-title-group>
<issn publication-format="electronic" pub-type="epub">1215-1215</issn>
<publisher>
<publisher-name>A publisher</publisher-name>
</publisher>
</journal-meta>
<article-meta>
<title-group>
<article-title xml:lang="es">The title</article-title>
</title-group>
<contrib-group>
<contrib contrib-type="author">
<contrib-id contrib-id-type="orcid">0000-0001-9343-8658</contrib-id>
<name>
<surname>Messi</surname>
<given-names>Lionel</given-names>
</name>
<xref ref-type="aff" rid="aff-aff1"/>
<email>name@gmail.com</email>
</contrib>
<aff id="aff-aff1">
<institution-wrap>
<institution>Selección Argentina de Fútbol</institution>
</institution-wrap>
</aff>
</contrib-group>
<pub-date pub-type="epub" date-type="pub" publication-format="electronic">
<year>2023</year>
</pub-date>
<elocation-id>20201</elocation-id>
<permissions>
<license xlink:href="https://creativecommons.org/licenses/by-nc/3.0/">
<ali:license_ref>https://creativecommons.org/licenses/by-nc/3.0/</ali:license_ref>
<license-p>Esta obra está bajo una Licencia Creative Commons Atribución-NoComercial 3.0 Internacional.</license-p>
</license>
</permissions>
</article-meta>
</front>
<body>
<sec id="introducción">
  <title>Introducción</title>
<p>Text.</p>
<table-wrap id="TAB_02">
  <label>Tabla 0.</label>
  <caption><title>Titulo de la segunda tabla </title></caption>
  <table style="border-collapse: collapse; border: none; border-spacing: 0px;">
  	<tbody>
  		<tr>
  			<td>
  				Column 1 
  			</td>
  			<td>
  				Column 2
  			</td>
  			<td>
  				Coloun 3
  			</td>
  		</tr>
  		<tr>
  			<td colspan="3" style="padding-right: 3pt; padding-left: 3pt;">
    This is only a line with a <break>
  				break.
  			</td>
  		</tr>
  	</tbody>
  </table></table-wrap>
</sec>
</body>
<back>
</back>
</article>


```

**Comment by fred-atherden** [comment]
Thanks for the bug report @estedeahora. I can reproduce the error. 

@hubgit any ideas what might be going wrong here?

**Comment by estedeahora** [comment]
I found that if I add two tags (one closing and one opening) it stops giving the error, but obviously it doesn't pass validation. Maybe this will give you a clue on how to fix it. This doesn't work if both tags are closing/opening tags. 

![image](https://github.com/JATS4R/jats-schematrons/assets/56130517/9e2ea3d4-d4cd-42f1-82d2-557a089e4f56)

**Comment by estedeahora** [comment]
Hello again, 

I just noticed that the problem is due to my wrong use of tags in `xml`. In `xml `it is mandatory to close tags (even those that are not paired). So, when we use `<break />` the problem disappears.  The habit of `html `made me forget this. Sorry for the mistake and thanks again for the work.

**Comment by fred-atherden** [comment]
Ah - good to know, and no problem - thanks. 

(I don't have permission to close the ticket so hopefully someone who does will do so when they come across this).
