### ISSUE TITLE
COI-statement bug

### ISSUE THREAD

**Issue by estedeahora** [JATS4R/jats-schematrons#31]
The [COI statement recommendation](https://jats4r.niso.org/conflict-of-interest-statements/) indicates that the value of the fn-type attribute should be "COI-statement". However, the [DTD1.3](https://jats.nlm.nih.gov/publishing/tag-library/1.3/attribute/fn-type.html) says that this is not a valid value and that the valid value is "coi-statement". As a consequence, the validator cannot be passed, because if "coi" is set then it is rejected by "JATS4R Schematron", but if "COI" is set then it is rejected by "JATS DTD" ( images of both situations are attached). 

![image](https://github.com/JATS4R/jats-schematrons/assets/56130517/54083b5f-ce52-4eed-bf86-78f969934def)

![image](https://github.com/JATS4R/jats-schematrons/assets/56130517/10aeb717-8d17-40c2-9f51-cd2d0ba7de46)

I understand that the above is a validator bug that I believe can be corrected. In principle, I think the right thing to do is to correct Jats4r's recommendation, as it is a specification of the other.

**Comment by estedeahora** [comment]
I made a pull request that (I think) solves this problem. Note that this issue had already been identified in the comments of the recommendation itself and in the comments of the "validator" section (both on the jats4r page). To be completed, this would require changes to the [recommendation itself](https://jats4r.niso.org/conflict-of-interest-statements/).

**Comment by estedeahora** [comment]
Thanks @fred-atherden. When does this PR go into production? The recommendation needs to be modified as well (from what I could read this is a constraint that was incorporated in DTD 1.3). How is this done to make the validator and the recommendation compatible?

**Comment by hubgit** [comment]
For reference, from [PubMed Central's tagging guidelines](https://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/dobs.html):

> Conflict of Interest statements should always be identified with the appropriate content type attribute, depending on the element. For Conflict of Interest statements captured as footnotes (`<fn>`) specify `@fn-type="coi-statement"` if tagged in the Journal Publishing (Blue) DTD 1.2 or newer, `@fn-type="conflict"` if tagged in the Journal Publishing (Blue) DTD 1.1 or older, or `@fn-type="COI-statement"` if tagged in the Journal Archiving (Green) DTD.

<img width="921" alt="image" src="https://github.com/JATS4R/jats-schematrons/assets/14294/2205b2c7-e0ff-4a6c-a5e8-67d71402ec6f">

However, both versions [1.2](https://jats.nlm.nih.gov/archiving/tag-library/1.2/attribute/fn-type.html) and [1.3](https://jats.nlm.nih.gov/archiving/tag-library/1.3/attribute/fn-type.html) of the Journal Archiving (Green) DTD apparently use `coi-statement` rather than `COI-statement`, as far as I can tell, so I'm not sure where the recommendation came from.

**Comment by fred-atherden** [comment]
@estedeahora, Alf has kindly deployed the update now. You should see the related change - feel free to reopen the issue if you spot any further issues. 

I understand the recommendation has also been updated to reflect the change in value. 

(Good to know, thanks Alf. I'm also not sure where the recommendation came from)

**Comment by estedeahora** [comment]
Yes, it works now! The recommendation was also updated. Thank you
